//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesFormulas
    {
        public int IdDetalle { get; set; }
        public int IdFormula { get; set; }
        public int IdInsumo { get; set; }
        public decimal CantidadInsumo { get; set; }
        public string UnidadMedidaInsumo { get; set; }
        public decimal CostoInsumo { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> IdUsuarioCreo { get; set; }
        public Nullable<System.DateTime> FechaCreo { get; set; }
        public Nullable<int> IdUsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual Formulas Formulas { get; set; }
        public virtual Insumos Insumos { get; set; }
    }
}
