//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formulas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Formulas()
        {
            this.DetallesFormulas = new HashSet<DetallesFormulas>();
            this.ProductosTerminados = new HashSet<ProductosTerminados>();
        }
    
        public int IdFormula { get; set; }
        public string NombreFormula { get; set; }
        public System.DateTime FechaElaboracion { get; set; }
        public decimal Cantidad { get; set; }
        public string Capacidad { get; set; }
        public string UnidadMedida { get; set; }
        public decimal CostoTotal { get; set; }
        public int IdFamilia { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesFormulas> DetallesFormulas { get; set; }
        public virtual FamiliaFormulas FamiliaFormulas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductosTerminados> ProductosTerminados { get; set; }
    }
}
