//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sdprolizaEntities : DbContext
    {
        public sdprolizaEntities()
            : base("name=sdprolizaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DetallesFormulas> DetallesFormulas { get; set; }
        public virtual DbSet<DetallesProductos> DetallesProductos { get; set; }
        public virtual DbSet<FamiliaFormulas> FamiliaFormulas { get; set; }
        public virtual DbSet<FamiliaInsumos> FamiliaInsumos { get; set; }
        public virtual DbSet<Formulas> Formulas { get; set; }
        public virtual DbSet<Insumos> Insumos { get; set; }
        public virtual DbSet<ProductosTerminados> ProductosTerminados { get; set; }
    }
}
